//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT or IGNORE INTO ScheduledMatchTeams
        ///(ScheduledMatchId, TeamId, AorB) 
        ///values 
        ///(@ScheduledMatchId, @TeamId, @AorB);.
        /// </summary>
        internal static string InsertScheduledMatchTeam {
            get {
                return ResourceManager.GetString("InsertScheduledMatchTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM RunningGames AS games
        ///WHERE games.Id = @RunningGameId;.
        /// </summary>
        internal static string TestDeleteRunningGame {
            get {
                return ResourceManager.GetString("TestDeleteRunningGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM RunningGameTeams AS teams
        ///WHERE teams.RunningGameId = @RunningGameId.
        /// </summary>
        internal static string TestDeleteRunningGameTeams {
            get {
                return ResourceManager.GetString("TestDeleteRunningGameTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///games.Id AS RunningGame_Id,
        ///games.Half AS half,
        ///games.Turn AS turn,
        ///games.Division as division,
        ///games.RunningGameTournamentId as &quot;RunningGameTournament_Id&quot;,
        ///tourneys.GroupId as &quot;group&quot;,
        ///teams.Id as RunningGameTeam_Id,
        ///teams.Side as side,
        ///teams.Name as name,
        ///teams.Coach as coach,
        ///teams.Race as race,
        ///teams.Tv as tv,
        ///teams.Rating as rating,
        ///teams.Score as score,
        ///teams.Logo as logo,
        ///teams.LogoLarge as logolarge
        ///FROM RunningGames AS games
        ///INNER JOIN RunningGameTeams AS teams ON (teams.R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestSelectAllFromRunningGame {
            get {
                return ResourceManager.GetString("TestSelectAllFromRunningGame", resourceCulture);
            }
        }
    }
}
